plugins {
    id 'net.neoforged.moddev.legacyforge' version '2.0.107'
    id 'maven-publish'
    id 'me.modmuss50.mod-publish-plugin' version '0.8.4'
    id 'idea'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

legacyForge {
    version = project.minecraft_version + '-' + project.forge_version

    validateAccessTransformers = false

    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.parchment_minecraft_version
    }

    runs {
        client {
            client()

            systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
        }

        server {
            server()
            programArgument '--nogui'
            systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
        }

        gameTestServer {
            type = "gameTestServer"
            systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
        }

        data {
            data()
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }

        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        "${modid}" {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

mixin {
    add sourceSets.main, "${mod_id}.refmap.json"
    config "${mod_id}.mixins.json"
}

// Sets up a dependency configuration called 'localRuntime' and a deobfuscating one called 'modLocalRuntime'
// These configurations should be used instead of 'runtimeOnly' to declare
// a dependency that will be present for runtime testing but that is
// "optional", meaning it will not be pulled by dependents of this mod.
configurations {
    runtimeClasspath.extendsFrom localRuntime
}
obfuscation {
    createRemappingConfiguration(configurations.localRuntime)
}


repositories {
    mavenLocal()
    mavenCentral()
    maven {url = 'https://maven.tterrag.com/'}
    maven {url = 'https://maven.blamejared.com'}
    maven {url = "https://maven.jaackson.me"}
    maven {url = "https://maven.ryanliptak.com/"}
    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"
            }
        }
        filter {
            includeGroup "maven.modrinth"
        }
    }
    maven {url = "https://www.cursemaven.com"}
}

dependencies {
    compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:${mixin_extras_version}"))
    implementation(jarJar("io.github.llamalad7:mixinextras-forge:${mixin_extras_version}"))

    modImplementation(jarJar("com.tterrag.registrate:Registrate:${registrate_version}"))

    modImplementation("com.tterrag.registrate:Registrate:${registrate_version}")
    modImplementation("maven.modrinth:blueprint:${blueprint_version}")
    modImplementation("maven.modrinth:neapolitan:${neapolitan_version}")
    modImplementation("maven.modrinth:farmers-delight:${farmersdelight_version}")
    modImplementation("curse.maven:farmers-respite-551453:${farmersrespite_file}")
    modImplementation("maven.modrinth:gallery:1.0.3")
    modImplementation("maven.modrinth:create:mc1.20.1-6.0.8")

    modCompileOnly("mezz.jei:jei-${jei_minecraft_version}-common-api:${jei_version}")
    modCompileOnly("mezz.jei:jei-${jei_minecraft_version}-forge-api:${jei_version}")
    modLocalRuntime("mezz.jei:jei-${jei_minecraft_version}-forge:${jei_version}")
    modCompileOnly("squeek.appleskin:appleskin-forge:${appleskin_version}:api")
    modLocalRuntime("squeek.appleskin:appleskin-forge:${appleskin_version}")

    annotationProcessor( "org.spongepowered:mixin:0.8.5:processor")
}

jar {
    from "LICENSE"
    manifest {
        attributes([
                "Specification-Title"     : project.mod_id,
                "Specification-Vendor"    : project.mod_authors,
                "Specification-Version"   : "1",
                "Implementation-Title"    : project.mod_name,
                "Implementation-Version"  : "1",
                "Implementation-Vendor"   : project.mod_authors,
                "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ"),
                'MixinConfigs': "${mod_id}.mixins.json"
        ])
    }
}

processResources {
    var replaceProperties = [
            minecraft_version        : minecraft_version,
            minecraft_version_range  : minecraft_version_range,
            forge_version            : forge_version,
            forge_version_range      : forge_version_range,
            loader_version_range     : loader_version_range,
            mod_id                   : mod_id,
            mod_name                 : mod_name,
            mod_license              : mod_license,
            mod_version              : mod_version,
            mod_authors              : mod_authors,
            mod_description          : mod_description,
            "blueprint_version_spec":       blueprint_version_spec,
            "neapolitan_version_spec":      neapolitan_version_spec,
            "farmersrespite_version_spec":  farmersrespite_version_spec
    ]
    replaceProperties.put("file", [jarVersion: project.version])

    filesMatching(["META-INF/mods.toml"]) {
        expand(replaceProperties)
    }
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            artifactId = mod_id + "-" + minecraft_version
            from components.java
        }
    }
    repositories {
        maven {
            name "DragonsPlus"
            url "https://maven.dragons.plus/releases"
            credentials(PasswordCredentials)
            authentication {
                basic(BasicAuthentication)
            }
        }
    }
}

publishMods {
    file = reobfJar.archiveFile
    changelog = project.file("CHANGELOG.md").text
    version = mod_version
    type = STABLE
    displayName = "Respiteful ${mod_version} for ${minecraft_version}"
    modLoaders.add("forge")
    modLoaders.add("neoforge")

    curseforge {
        projectId = "836471"
        accessToken = providers.environmentVariable("CURSEFORGE_TOKEN")
        minecraftVersions.add(minecraft_version)

        requires {
            slug = "neapolitan"
            slug = "farmers-respite"
        }
    }

    modrinth {
        projectId = "Df7RucLK"
        accessToken = providers.environmentVariable("MODRINTH_TOKEN")
        minecraftVersions.add(minecraft_version)

        requires {
            slug = "neapolitan"
            slug = "farmers-respite"
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
