modLoader="javafml"
loaderVersion="${fml_version_spec}"
license="MIT"
issueTrackerURL="https://github.com/DragonsPlusMinecraft/Respiteful/issues"

[[mods]]
modId="respiteful"
version="${version}"
displayName="Respiteful"
#updateJSONURL="https://change.me.example.invalid/updates.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/respiteful"
logoFile="logo.png"
#credits="Thanks for this example mod goes to Java"
authors="${author}"
description='''
A Neapolitan add-on adding flavors from Farmer's Respite
'''

[[dependencies.respiteful]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_spec}"
    ordering="NONE"
    side="BOTH"

[[dependencies.respiteful]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_spec}"
    ordering="NONE"
    side="BOTH"

[[dependencies.respiteful]]
    modId="blueprint"
    mandatory=true
    versionRange="${blueprint_version_spec}"
    ordering="NONE"
    side="BOTH"

[[dependencies.respiteful]]
    modId="neapolitan"
    mandatory=true
    versionRange="${neapolitan_version_spec}"
    ordering="AFTER"
    side="BOTH"

[[dependencies.respiteful]]
    modId="farmersrespite"
    mandatory=true
    versionRange="${farmersrespite_version_spec}"
    ordering="AFTER"
    side="BOTH"
