modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/DragonsPlusMinecraft/Respiteful/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
#updateJSONURL="https://change.me.example.invalid/updates.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/respiteful"
logoFile="logo.png"
#credits="Thanks for this example mod goes to Java"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="blueprint"
    mandatory=true
    versionRange="${blueprint_version_spec}"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="neapolitan"
    mandatory=true
    versionRange="${neapolitan_version_spec}"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="farmersrespite"
    mandatory=true
    versionRange="${farmersrespite_version_spec}"
    ordering="AFTER"
    side="BOTH"
